from __future__ import annotations

from datetime import datetime, timezone
from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class RunStatus(StrEnum):
    started = "started"
    running = "running"
    completed = "completed"
    failed = "failed"
    fallback_completed = "fallback_completed"


class EventType(StrEnum):
    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"
    fallback_used = "fallback_used"


class AgentName(StrEnum):
    research = "research"
    buyer = "buyer"
    legal_risk = "legal_risk"
    advertising = "advertising"
    theme_design = "theme_design"
    score_launch = "score_launch"
    store_creator = "store_creator"


class Decision(StrEnum):
    launch = "launch"
    pause = "pause"
    reject = "reject"


class LaunchRequest(BaseModel):
    product_name: str = Field(default="Magnetic Phone Mount", min_length=1)


class AuthSignupRequest(BaseModel):
    email: str = Field(min_length=3, max_length=320)
    password: str = Field(min_length=8, max_length=256)
    full_name: str = Field(default="", max_length=120)


class AuthLoginRequest(BaseModel):
    email: str = Field(min_length=3, max_length=320)
    password: str = Field(min_length=1, max_length=256)


class AuthUser(BaseModel):
    id: UUID
    email: str
    full_name: str = ""


class AuthResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    user: AuthUser


class LaunchTriggerResponse(BaseModel):
    run_id: UUID
    status: RunStatus
    temporal_workflow_id: str


class PriceRange(BaseModel):
    low: float
    high: float


class ResearchOutput(BaseModel):
    product_name: str
    category: str
    trend_score: float = Field(ge=0.0, le=1.0)
    search_volume: int = Field(ge=0)
    social_mentions: int = Field(ge=0)
    competitor_summary: str
    price_range: PriceRange
    confidence: float = Field(ge=0.0, le=1.0)
    # Real product image URLs surfaced by Nimble's ShoppingResult.thumbnail.
    # Empty when Nimble had no shopping results for the query.
    product_images: list[str] = Field(default_factory=list)


class BuyerOutput(BaseModel):
    supplier_name: str
    unit_cost: float = Field(ge=0.0)
    shipping_days: int = Field(ge=0)
    rating: float = Field(ge=0.0, le=5.0)
    estimated_margin: float = Field(ge=0.0, le=1.0)
    margin_score: float = Field(ge=0.0, le=1.0)
    confidence_score: float = Field(ge=0.0, le=1.0)
    risk_flags: list[str] = Field(default_factory=list)


class RiskOutput(BaseModel):
    cleared: bool
    risk_score: float = Field(ge=0.0, le=1.0)
    flags: list[str] = Field(default_factory=list)
    recommendation: str


class ProductVariant(BaseModel):
    name: str
    price: float = Field(ge=0.0)
    blurb: str = ""
    badge: str = ""
    accent: str = "#0f766e"


class FAQItem(BaseModel):
    question: str
    answer: str


class Review(BaseModel):
    name: str
    rating: float = Field(ge=0.0, le=5.0)
    text: str


class AdvertisingOutput(BaseModel):
    product_name: str
    tagline: str
    description: str
    cta_text: str
    hero_image_prompt: str
    hero_image_url: str
    features: list[str] = Field(default_factory=list)
    specs: dict[str, str] = Field(default_factory=dict)
    variants: list[ProductVariant] = Field(default_factory=list)
    faq: list[FAQItem] = Field(default_factory=list)
    reviews: list[Review] = Field(default_factory=list)
    shipping_note: str = ""


class StoreTheme(BaseModel):
    """Per-store palette + typography tokens generated by the theme_design agent.

    All optional with sensible defaults; the storefront falls back to the
    existing teal palette when a token is missing or `theme` is None.
    """

    primary: str = "#0f766e"          # main brand accent (CTAs, eyebrow, checkmarks)
    accent: str = "#0d5d56"           # hover / secondary highlight
    bg: str = "#f8fafc"               # page background
    surface: str = "#ffffff"          # card / panel background
    text: str = "#0f172a"             # primary text
    text_muted: str = "#475569"       # secondary text
    border: str = "#e2e8f0"           # subtle dividers
    font_pair: str = "sans-modern"    # serif-elegant | sans-modern | mono-tech


class StoreOutput(BaseModel):
    store_id: UUID
    slug: str
    store_url: str
    product_name: str
    tagline: str = ""
    description: str
    price: float = Field(ge=0.0)
    hero_image_url: str
    supplier: str
    cta_text: str
    features: list[str] = Field(default_factory=list)
    specs: dict[str, str] = Field(default_factory=dict)
    variants: list[ProductVariant] = Field(default_factory=list)
    faq: list[FAQItem] = Field(default_factory=list)
    reviews: list[Review] = Field(default_factory=list)
    shipping_note: str = ""
    theme: StoreTheme | None = None


class LaunchScoreOutput(BaseModel):
    launch_score: float
    decision: Decision


class AgentEvent(BaseModel):
    model_config = ConfigDict(use_enum_values=True)

    agent_name: AgentName
    event_type: EventType
    message: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    payload: dict[str, Any] = Field(default_factory=dict)


class AgentEventsResponse(BaseModel):
    run_id: UUID
    events: list[AgentEvent]


class LaunchRun(BaseModel):
    model_config = ConfigDict(use_enum_values=True)

    run_id: UUID
    temporal_workflow_id: str
    product_name: str
    slug: str
    status: RunStatus
    launch_score: float | None = None
    decision: Decision | None = None
    store_url: str | None = None
    error: str | None = None
    # Batch deployment fields — present when this run was part of a batch.
    batch_id: UUID | None = None
    batch_slot: int | None = None      # 0-indexed slot position in the batch
    attempt_index: int = 1             # Nth overall pipeline run in this slot (1, 2, 3, ...)
    product_attempt: int = 1           # 1 or 2 — which retry on the CURRENT product (plan 04)
    products_tried: int = 1            # how many distinct products this slot has tried (plan 04)
    # Businesses portfolio lifecycle (Phase D).
    business_status: str = ""          # '' | 'live' | 'shutdown' | 'archived'
    launched_at: datetime | None = None
    shutdown_at: datetime | None = None
    shutdown_reason: str = ""


class BatchTriggerRequest(BaseModel):
    count: int = Field(default=5, ge=1, le=20)
    threshold: float | None = Field(default=None, ge=0.0, le=1.0)
    products: list[str] | None = None  # explicit candidate queue; otherwise drawn from Trend Scout


class BatchSlotSummary(BaseModel):
    """One slot's current state in a batch (used in the create response)."""
    slot: int
    run_id: UUID
    product_name: str


class BatchTriggerResponse(BaseModel):
    batch_id: UUID
    target_count: int
    threshold: float
    slots: list[BatchSlotSummary]


class BatchStatusResponse(BaseModel):
    batch_id: UUID
    target_count: int
    threshold: float
    runs: list[LaunchRun]


class WorkflowInput(BaseModel):
    run_id: UUID
    product_name: str
    temporal_workflow_id: str


class WorkflowResult(BaseModel):
    run: LaunchRun
    events: list[AgentEvent]
    store: StoreOutput | None = None
